name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8abaab53bf490a1b20799889fa56764ffc0cb99eebc6ddd2641e9200955fc931"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
