name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "722deb7581ec9187c7e7c917b078acbe710f7e4acca506fa3cbe0ad3f5c70cbc"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
